# Generated by Django 4.2.28 on 2026-02-24 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий проверки'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
