# Generated by Django 4.2.28 on 2026-02-28 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='alternative_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Альтернативный email'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
