# Generated by Django 4.2.28 on 2026-02-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-pub_date'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
