# Generated by Django 4.2.28 on 2026-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parentprofile_alternative_email_and_more'),
        ('main', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher schedule',
                'verbose_name_plural': 'Teacher schedules',
                'unique_together': {('teacher', 'week_start_date')},
            },
        ),
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.CreateModel(
            name='TeacherScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.teacherschedule')),
            ],
            options={
                'verbose_name': 'Teacher schedule slot',
                'verbose_name_plural': 'Teacher schedule slots',
                'unique_together': {('schedule', 'day_of_week', 'hour')},
            },
        ),
    ]
