# Generated by Django 4.2.28 on 2026-04-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parentprofile_alternative_email_and_more'),
        ('main', '0003_teacherschedule_alter_newsmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(default='Занятие', max_length=200, verbose_name='Предмет/занятие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.teacherscheduleslot', verbose_name='Слот расписания преподавателя')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.studentprofile', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Запись ученика на занятие',
                'verbose_name_plural': 'Записи учеников на занятия',
                'unique_together': {('student', 'schedule_slot')},
            },
        ),
    ]
